# constants/student_constants.py
from fastapi import status

# Success
HTTP_OK = status.HTTP_200_OK
HTTP_CREATED = status.HTTP_201_CREATED
HTTP_ACCEPTED = status.HTTP_202_ACCEPTED
HTTP_NO_CONTENT = status.HTTP_204_NO_CONTENT

# Client Errors
HTTP_BAD_REQUEST = status.HTTP_400_BAD_REQUEST
HTTP_UNAUTHORIZED = status.HTTP_401_UNAUTHORIZED
HTTP_FORBIDDEN = status.HTTP_403_FORBIDDEN
HTTP_NOT_FOUND = status.HTTP_404_NOT_FOUND

# Server Errors
HTTP_INTERNAL_SERVER_ERROR = status.HTTP_500_INTERNAL_SERVER_ERROR
